### ISSUE TITLE
"AnsibleUndefinedVariable: 'list object' has no attribute 'kerberos_realm'"

### ISSUE THREAD

**Issue by changchichung** [mrlesmithjr/ansible-samba#4]
I did define kerberos_realm in default/main.yml

```
# defaults file for ansible-samba
 pri_domain_name: res.com.tw
 samba_ad_info: []
    ad_dc_hostname: "{{ ansible_hostname }}"
    ad_dns_domain_name: "{{ pri_domain_name }}"
    adminpass: adminpass
   # allow_dns_updates: disabled
    backend_dns: internal
    dns_forwarder: 8.8.8.8
    #kerberos_realm: '{{ pri_domain_name }}'
    kerberos_realm: res.com.tw
    netbios_domain_name: "{{ samba_netbios_domain_name[0]|upper }}"
```
but there`s an error like below

TASK [ansible-samba : config_samba | configuring samba] ********************************************************************************************************
fatal: [hqs243.res.com.tw]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'kerberos_realm'"}

any suggestions ?

**Comment by mrlesmithjr** [comment]
You need to remove the `[]` after the variable `samba_ad_info` otherwise that variable is undefined.

So you should have
```yaml
# defaults file for ansible-samba
 pri_domain_name: res.com.tw
 samba_ad_info:
    ad_dc_hostname: "{{ ansible_hostname }}"
    ad_dns_domain_name: "{{ pri_domain_name }}"
    adminpass: adminpass
   # allow_dns_updates: disabled
    backend_dns: internal
    dns_forwarder: 8.8.8.8
    #kerberos_realm: '{{ pri_domain_name }}'
    kerberos_realm: res.com.tw
    netbios_domain_name: "{{ samba_netbios_domain_name[0]|upper }}"
```

Hope this helps.

**Comment by changchichung** [comment]
sorry , it`s the same.

a little more log 

```
<hqs243.res.com.tw> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/home/minion/.ansible/cp/c34df203e3 hqs243.res.com.tw '/bin/sh -c '"'"'rm -f -r /home/minion/.ansible/tmp/ansible-tmp-1523501904.4702783-73848672937187/ > /dev/null 2>&1 && sleep 0'"'"''
<hqs243.res.com.tw> (0, b'', b'')
fatal: [hqs243.res.com.tw]: FAILED! => {
    "changed": false,
    "msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'kerberos_realm'"
}
```

**Comment by mrlesmithjr** [comment]
try removing your `kerberos_realm` and put the default back and test. I am sure it will do the same but not sure why. I use this role quite often without issues so I may need to test. You don't have any group_vars or host_vars do you by chance?

**Comment by changchichung** [comment]
i had already roll back to the default ```'{{ pri_domain_name }}'```
but it`s the same situation.

**Comment by changchichung** [comment]
i try to define kerberos_realm = mydomain.com.tw in vars/main.yml , default/main.yml , and the vars section in playbook , none works. still not get the attribute kerberos_realm

**Comment by mrlesmithjr** [comment]
I just tried the following playbook without any issues using this role. So I am not sure what is going on for you. This sounds like something outside of the role potentially. I would delete the role, clone the role back again, use group_vars to define the variables, and test again.

```yaml
---
- hosts:                            samba_domain_controllers
  vars:
    # defaults file for ansible-samba
    pri_domain_name:                res.com.tw
    samba_ad_info:
      ad_dc_hostname:               "{{ ansible_hostname }}"
      ad_dns_domain_name:           "{{ pri_domain_name }}"
      adminpass:                    "P@55w0rd123"
     # allow_dns_updates:           disabled
      backend_dns:                  internal
      dns_forwarder:                8.8.8.8
      kerberos_realm:               '{{ pri_domain_name }}'
      netbios_domain_name:          "{{ samba_netbios_domain_name[0]|upper }}"

    # Defines if you are building an Active Directory domain controller
    samba_create_domain_controller: true

    # Defines server role
    # (standalone server or active directory domain controller)
    samba_server_role:              active directory domain controller

  roles:
    - role:                         ansible-samba
      become:                       true
```
